FROM fluent/fluentd:v1.11.5-1.0

USER root

RUN gem install fluent-plugin-elasticsearch --no-document \
    && gem sources --clear-all \
    && rm -rf /usr/lib/ruby/gems/*/cache/*.gem

#COPY ./fluent.conf /fluentd/etc/fluent.conf
